* Adam Tindale
** Updates! <2025-06-01 Sun> 
Hey Adam!

How's it going? 

I am travelling to Vancouver tomorrow, and will be back on the 9th, and then flying back to India on the 20th. The week after coming back is looking a little tight so I'm not sure I'll be able to join you to work on the keyboards this time, but if you're planning to work there during that time I'll try to drop by to see you one of the days!

In other news I'm going through the K&R C book and have been having alot of fun. At some point I side tracked and made this snake game:

[video link]

And then got distracted further and tried to see how hard it would be to do some network requests in C, turns out not as hard as I thought (had some help from libcurl and cJSON). Ambitious goal is to re-write a node based offline proxy server I have for Are.na in C this summer. How hard can strings really be? I'll update you in two months :) 

Hopefully will be making my way through the SICP book over the summer and In preparation I've been tinkering with emacs (evil-mode) and playing around with the emacs lisp, which has been great fun! This live environment stuff is bonkers! What do you mean I can just execute code and make things happen in this editor! crazy... I think you can do similar stuff in neovim with lua as well but I never got into it, this feels quite intuitive.

Anyways, let me know if you're planning to be at x-fab in june, will try to drop by!

best,
Aaryan

* Jer
** Website thingige
Hi Jer! 
I’m doing good, hope you are well too :)

Very exciting to hear from you, this sounds like an awesome project, and I’d love to chat and help/collaborate in any way possible. I would want to know more about the creative lab you are working on so I can give more specific ideas. 

But till then, some thoughts of the top of my head…

First of all I’m curious how the hosting for option 1 would work. I don’t have much experience with WebRTC or Touchdesigner but I'm guessing if you're planning to use Touchdesigner you would need some kind of server setup? Is this something that is within the bounds of this website?

I'm not sure if you've seen this, mediapipe also has a js implementation that works in the browser, which is awesome! Although ml5.js is pretty good itself too.

https://github.com/pjbelo/mediapipe-js-demos

I've played around with the ml5 hand/posenet before but just to toy around and experiment, nothing concrete though. I'm always reluctant to explore webcam based interaction (as a primary method of interaction) for any public facing websites for a few reasons. I think people generally are not very keen on giving webcam access for browsing websites. When people do, gesture based navigation tends to be flaky at times, for instance it won't work in low-light situations or if you have an oldish webcam, etc. And sometimes you just don't have access to a webcam, if say you're browsing on your monitor or something of sorts.

But regardless of all of this, I think it makes for a very exciting interaction when it works. I haven't seen (m)any interesting implementations previously done so I'd be very keen on seeing how something like this plays out and would love to explore alongside as well. 

Something that does come to mind though is this website I saw some time back, but seems like it doesn't work anymore. From when I saw it, a montage would play as long as you kept smiling.

https://deathofmygeneration.fun/
https://cthdrl.co/jagwartwin-happyface/

Beyond the gesture based interactions, riffing of the word 'alive' in context of websites... I think of it in two ways... one obviously being the opposite of static, being dynamic which there's plenty of examples to look at. Some that come to mind:

https://patrickheng.com/
https://12.berlinbiennale.de/
https://www.vooo.space/
https://mfabiennial2023.risd.gd/

I also really like thinking of alive in the sense of websites responding to their environment, Yehwan Song's work comes to mind:

https://yhsong.com/

She has a lot of installation work but the browser based work is really interesting.

I'm not sure if you have a technical audience, if so, I've been wanting to make a website for a while that would be navigable from the browser devtools console, as in instructions and relevant information would be console logged and functions would be exposed globally that could be executed by typing them in the console.

This website/tool I recently came across (which is super cool itself) implements the executable functions from the console thing.
https://raphaelbastide.com/cascade/


