* Progress is a flawed notion
Progress is a concept that propels the narratives of our time. It is understood that making progress is the solution to global problems. However if we were to understand the metric or measure of progress, we would find that it is very murky.
# complete sentence here

** Assumes a linear time 
Progress or the idea of progress means that there is an understanding of time that is travelling form one point (start) to another (destiny). Time on the other hand doesn't function this way.

**** Time is divided and made legible
To understnad time, or make sense of it we divide 

**** Spatial movement and energy is coordinated

** The myth of history
History history, history... just repeats itself. If it has to be repeated, it means it hasn't been (*) _overcome_ . 

History is only what has been recorded, and what has been synthesized from a certain point of view. So if the subset of history that is recorded, narrowed down further by taking a point of view. Point of view, or interpretation isn't something we can escape, however the problem is that history is _presented not as an interpretation_, this is problematic...

History is appropriated and reappropriated by the cultural and politics of any given time.

**** Notes
***** overcome:
Perhaps not the word I want to use. essentially that it repeats itself means we have not moved past, we have not turned to direction, we are perhaps circulating, revolving.

** Technological, medical and scientific progress
** Excerpt
*** https://doubleblindmag.com/colonialism-by-another-name/
'Throughout the period of colonialism, which, in different forms, continues to this day, and is more aptly described as on-going coloniality, the dominance of this single story spread across the globe and was violently foisted upon those deemed “non-modern” or less than fully human, according to the hierarchical standards set by the leaders of Western modernity. Within this modern/colonial imaginary, everyone that is not white and not ascribing to the same dominant beliefs, knowledge, and value systems of Christian Europeans and their colonial descendants is deemed as lacking full humanity. Education and mass media continue to perpetuate and legitimize the assimilation and annihilation of all non-modern modes of existence.'

