* Progress is a flawed notion
Progress is a concept that propels the narratives of our time. It is understood that making progress is the solution to global problems. However if we were to understand the metric or measure of progress, we would find that it is very murky.
# complete sentence here

** Assumes a linear time 
Progress or the idea of progress means that there is an understanding of time that is travelling form one point (start) to another (destiny). Time on the other hand doesn't function this way.

**** Time is divided and made legible
To understnad time, or make sense of it we divide 

**** Spatial movement and energy is coordinated

** The myth of history
History history, history... just repeats itself. If it has to be repeated, it means it hasn't been (*) _overcome_ . 

History is only what has been recorded, and what has been synthesized from a certain point of view. So if the subset of history that is recorded, narrowed down further by taking a point of view. Point of view, or interpretation isn't something we can escape, however the problem is that history is _presented not as an interpretation_, this is problematic...

History is appropriated and reappropriated by the cultural and politics of any given time.

**** Notes
***** overcome:
Perhaps not the word I want to use. essentially that it repeats itself means we have not moved past, we have not turned to direction, we are perhaps circulating, revolving.

** Technological, medical and scientific progress


** 
