* Workshop 
** Notes
*** Key points
Explore procedural book making
emergent, play, collage within mechanical systems (venn diagram)
-> Quote huzinga
focus on commincation and presentation
*** General notes
- Play, experiment and explore, but lean on the side of communicating what you're doing and it's presentation
- Keep making stuff, but also present them. As zines, newsprints, posters, etc. All outcomes to be frozen(print/image/mp4), if there is interactive components, make sure to document it with steps for reproduction.
- Keep (I) for breadth and exploration, make divergent jumps and try different small experiments
- Keep (II) for depth & presentation, explore projects in (I) more thoroughly, present well, and stitch together to make a coherent point (or not).
  
*** Sparse notes
- Execute computations physically
- Excel sheets, table generated printed out... Can be filled in with text and then can be scanned, do simple ocr and have easy access for data visualisation and stuff and also ease of handwriting... Can go further and think about what ways to interpret hand drawings/writing...  
- Printing methods based on print masters and stuff, but perhaps with paper. Eg. ink transfer kind of stuff. Waxy prints, negative for water based smth to pass thru and print? a sieve sort of? Ponder...
- Algorithms, physarium, WFC, its explainations as zines. Zines may incorporate these algorithms in its structure
  
*** Exercises
- Explore Physarium Algorithm
- Use it to create layouts
- Explore creating matrix with book spreads, x, y, z (3 dimensional matrix... space... math stuff?) 
- Desiginig italo calvino's books and incorporating structure of narrative or space in his books into the structure/form of the book
- Wave function collapse with book spreads + spread layouts even... like taxonomic informations systems or puzzle books or smth. (RM book ali class)
- Publishing a paper on procedural bookmaking?
- What is the relationship of sin/cos and circles
  
*** Not to do
- Don't try to create one big thing (smaller sketches)
- Don't try to make a monolithic software
- small iterations of software
- Don't write to justify, write to reflect
- Don't write to create meaning, write to communicate what's important, how stuff coheres and why it matters (to me)
  
*** outcomes
- Software sketches
- Publications
- Algorithms
- Writings
- Paper
*** learning outcomes
- Technical skillz in context of graphic design

** Study Proposal
*** Front
(loose thread of notes, to do's and dont's + references)
format: [interview | essay | reverse annotation]
*** Index
*** What are you going to make?
I'm going to be making publications, zines, newsprints, posters, websites, software sketches, maybe some form of printing aparatus and some writings (perhaps a techincal paper (We'll see, i'd want to take a shot at that)). 

*** What is your work aiming to do?
Explore and reveal computations the form and structure of the book are capable of. 
For instance,
1. it can compute odd or even based on side of the page (recto odd, verso even)
2. offsetting sheet, light shining through can plot offset position of pages - can be utilised as interactive arithmetics or vector math computation...
3. Excel/spreadsheet/db kind of thing
4. OR/NOT/AND kind of stuff + Josef albers color?

*** If you had to give a statement for the line of study you are going to conduct ---
Explore procedural book making by conducting (emergent, collage) play within a mechanical systems (venn diagram)

(reference: Huzinga)
"the designer constructs a system of constraints, such as a simulation or a set of simple instructions, and then allows the player actively to learn by exploring and tinkering with the system. In each case, there is no prior "course content" to be learnt, no predefined terminus of the process, only a rough specification of the general region to be explored, and so the player's individual trajectory may surprise even the designer."

“Play is a way of operating a constrained system in a gratifying way.” Bogost

*** Do you have any general notes or terms that you have set for yourself?
1. Play, experiment and explore, but lean on the side of communicating what you're doing and it's presentation
2. Keep making stuff, but also present them. As zines, newsprints, posters, etc. All outcomes to be frozen(print/image/mp4), if there is interactive components, make sure to document it with steps for reproduction.
3. Keep W(I) for breadth and exploration, make divergent jumps and try different small experiments
4. Keep W(II) for depth & presentation, explore projects in W(I) more thoroughly, present well, and stitch together to make a coherent point (or not).

*** List of example exercises / todos
- Somehow find a slime mold and see if you can interact with it for some form of navigational design (navigation of book?)
- Explore Physarium Algorithm and use it to create layouts (spreads/inter-spreads)
- Explore creating matrix with book spreads, x, y, z (3 dimensional matrix. math stuff?) 
- Wave function collapse with book spreads + spread layouts even...
  like taxonomic informations systems or puzzle books or smth. (RM book ali class)
- Excel sheets, table generated printed out... Can be filled in with text and then can be scanned, do simple ocr and have easy access for data visualisation and stuff and also ease of handwriting...
  Can go further and think about what ways to interpret hand drawings/writing...  
- Executing computations physically. 
- Printing methods based on print masters and stuff, but perhaps with paper. Eg. ink transfer kind of stuff. Waxy prints, negative for water based smth to pass thru and print? a sieve sort of? Ponder...
- Desiginig italo calvino's books and incorporating structure of narrative or space in his books into the structure/form of the book
- Publishing a paper on procedural bookmaking?
- What is the relationship of sin/cos and circles
- Voronoi typesetting/layouting?
- Lisajous curve table for typographic ratios
- Algorithms: physarium, WFC, its explainations as zines. Zines may incorporate these algorithms in its structure
- making a super constrained model to run on a rasberri pi, assigning parameters to contrast (contrast as weight difference, size difference etc) and variations, business... and then training this model and running it. Not to run well but just to see how it works.


