* Workshop 
** Notes
*** Key points
Explore procedural book making
emergent, play, collage within mechanical systems (venn diagram)
-> Quote huzinga
focus on commincation and presentation
*** General notes
- Play, experiment and explore, but lean on the side of communicating what you're doing and it's presentation
- Keep making stuff, but also present them. As zines, newsprints, posters, etc. All outcomes to be frozen(print/image/mp4), if there is interactive components, make sure to document it with steps for reproduction.
- Keep (I) for breadth and exploration, make divergent jumps and try different small experiments
- Keep (II) for depth & presentation, explore projects in (I) more thoroughly, present well, and stitch together to make a coherent point (or not).
  
*** Sparse notes
- Execute computations physically
- Excel sheets, table generated printed out... Can be filled in with text and then can be scanned, do simple ocr and have easy access for data visualisation and stuff and also ease of handwriting... Can go further and think about what ways to interpret hand drawings/writing...  
- Printing methods based on print masters and stuff, but perhaps with paper. Eg. ink transfer kind of stuff. Waxy prints, negative for water based smth to pass thru and print? a sieve sort of? Ponder...
- Algorithms, physarium, WFC, its explainations as zines. Zines may incorporate these algorithms in its structure
  
*** Exercises
- Explore Physarium Algorithm
- Use it to create layouts
- Explore creating matrix with book spreads, x, y, z (3 dimensional matrix... space... math stuff?) 
- Desiginig italo calvino's books and incorporating structure of narrative or space in his books into the structure/form of the book
- Wave function collapse with book spreads + spread layouts even... like taxonomic informations systems or puzzle books or smth. (RM book ali class)
- Publishing a paper on procedural bookmaking?
- What is the relationship of sin/cos and circles
  
*** Not to do
- Don't try to create one big thing (smaller sketches)
- Don't try to make a monolithic software
- small iterations of software
- Don't write to justify, write to reflect
- Don't write to create meaning, write to communicate what's important, how stuff coheres and why it matters (to me)
  
*** outcomes
- Software sketches
- Publications
- Algorithms
- Writings
- Paper
*** learning outcomes
- Technical skillz in context of graphic design

** Study Proposal
*** Front
(loose thread of notes, to do's and dont's + references)
format: [interview | essay | reverse annotation]
*** Index
*** What are you going to make?
Through the course of the study I will be making publications, zines, newsprints, posters, websites, software sketches. Maybe some form of a printing aparatus and some writings (includeing a TBD techincal paper). 

// be more specific

*** What is your work aiming to do?
Investigate whether (constrained computational tools[&/]environments) can produce forms* of publications that can stand as alternatives to digital computational practices, in doing so expanding the domain of computation into print and engage the body and material in the process.

// for instance
1. Books in their structure compute odd or even as the side of the page (recto odd, verso even)
2. Excel/spreadsheet/db kind of thing
3. OR/NOT/AND kind of stuff + Josef albers color?

Catalgoue various forms of books, the properties that emerge from such alternative structures of books and how it affects organisation and interpretations of the.

// for instance
offsetting sheet, light shining through can plot offset position of pages - can be utilised as interactive arithmetics or vector math computation.

   

*** Elaborate on the approach or lens you will be conducting\this study from.
(reference: Huzinga)
"the designer constructs a system of constraints, such as a simulation or a set of simple instructions, and then allows the player actively to learn by exploring and tinkering with the system. In each case, there is no prior "course content" to be learnt, no predefined terminus of the process, only a rough specification of the general region to be explored, and so the player's individual trajectory may surprise even the designer."



Procedural book making by creating enviroments for play (emergent, collage) within a mechanical systems (venn diagram)

“Play is a way of operating a constrained system in a gratifying way.” Bogost

*** How does this contextualise in current times and local space 
(in response to: Appendix A: Roderick's email)

*** Axioms
1. Algorithms predate computers.
2. Books come in various forms. 

*** Do you have any general notes or terms that you have set for yourself?
1. Play, experiment and explore, but lean on the side of communicating what you're doing and it's presentation
2. Keep making stuff, but also present them. As zines, newsprints, posters, etc. All outcomes to be frozen(print/image/mp4), if there is interactive components, make sure to document it with steps for reproduction.
3. Do simple things, do them well
4. Keep W(I) for breadth and exploration, make divergent jumps and try different small experiments
5. Keep W(II) for depth & presentation, explore projects in W(I) more thoroughly, present well, and stitch together to make a coherent point (or not).

*** List of example exercises / todos
1. Somehow find a slime mold and see if you can interact with it for some form of navigational design (navigation of book?)
2. Explore Physarium Algorithm and use it to create layouts (spreads/inter-spreads)
   https://www.sciencedirect.com/science/article/abs/pii/S2210650221000511

3. Explore creating matrix with book spreads, x, y, z (3 dimensional matrix. math stuff?) 
   I don't know how this works, will have to study a little. But essentially, there would be a few dimensions,
   - the spread which is the visual spread that appears and you design on,
   - then the actual sheets before they are bound.
   - Z axis relationships between individual pages.
   And if you have a representation for this, you can use this space for physarium algorithms.

4. Wave function collapse with book spreads + spread layouts even...
   like taxonomic informations systems or puzzle books or smth. (RM book ali class)

5. Excel sheets, table generated printed out... Can be filled in with text and then can be scanned, do simple ocr and have easy access for data visualisation and stuff and also ease of handwriting...
   Can go further and think about what ways to interpret hand drawings/writing...  

6. Executing computations physically. 
   Like the typesize + leading relationship wheel, or graph multiplication, addition and stuff.

7. Printing methods based on print masters and stuff, but perhaps with paper. Eg. ink transfer kind of stuff. Waxy prints, negative for water based smth to pass thru and print? a sieve sort of? Ponder...

8. Desiginig italo calvino's books, or Arcadia  and incorporating structure of narrative or space in his books into the structure/form of the book
   https://en.wikipedia.org/wiki/Arcadia_(play)

9. Publishing a paper on procedural bookmaking?

10. What is the relationship of sin/cos and circles
    I'm just curious, probably a quick exercise and a quick zine (1 day project)

11. Voronoi typesetting/layouting?
    Use voronoi algorithms for typesetting text. Maybe plot text on points, or create a grid/structure using the algorithm and play in it.

12. Lisajous curve table for typographic ratios
    https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Lissajous_phase.svg/1200px-Lissajous_phase.svg.png
    The above as an interface to typography? Blackburn pendulum?

13. Algorithms: physarium, WFC, its explainations as zines. Zines may incorporate these algorithms in its structure
14. making a super constrained model to run on a rasberri pi, assigning parameters to contrast (contrast as weight difference, size difference etc) and variations, business... and then training this model and running it. Not to run well but just to see how it works.
15. How would saddle stitch pages sound if it was a rhythm (drum beat or smth) 
16. Paper sizes, where do they come from?

*** General notes, thoughts
- Abstraction like Math or Programming creates lenses for interpretation and helps in creation of meaningful play-grounds. Meaningful being, systems that can support interpretation of what the play performed could mean. The play that is performed however is the grounds for the actual making. Abstraction is the grid structure, play is the enactment of (FW) within this structure to produce something.

*** Not to do
- Don't try to create one big thing (smaller sketches)
- Don't try to make a monolithic software
- small iterations of software
- Don't write to justify, write to reflect
- Don't write to create meaning, write to communicate what's important, how stuff coheres and why it matters (to me)
